PATH1 = ~/xMyWorkSpace/System_Software/Lab2/questions/11/src1
PATH2 = ~/xMyWorkSpace/System_Software/Lab2/questions/11/src2
PATH3 = ~/xMyWorkSpace/System_Software/Lab2/questions/11/src3

all:hellomake

hellomake:
	make -C $(PATH1) 
	make -C $(PATH2) 
	make -C $(PATH3)

clean:
	make clean -C $(PATH1)
	make clean -C $(PATH2)
	make clean -C $(PATH3)
